---
title: "Tweeter for Texas Shooting"
author: "Eunsik Na"
date: "November 15, 2017"
output: html_document
---

Words that address the shooting in Twitter

#prayfortexas
My heart is with the victims.
Heartbreaking
My thoughts and prayers are with texas. It is so heartbreaking, all these kind of tragedies are happening way too often.

Reasons why I think #prayfortexas is important.
There are several tweets dealing with consolation for shooting in texas occurred in November 5th, 2017. Of course if there is a tradegy such as shootings, people usually tweet on twiiter to comfort people who lost their friends or families in the event of shootings.


#GunControlNow
Here is a SINGLE reason why NOTHING is happening after these mass shootings. It's not the 2nd Amendment, It's Money & Greed.
When drunk driving became an issue, laws were written. Why is gun crime the ONLY thing govt. won't even talk about?! NRA = money.
Fact: Thoughts & prayers have never prevented a mass shooting. Laws have. 
Isn't is strange how mental illness doesn't massacre anyone in Canada, Australia, or the United Kingdom?

Reasons why I think $GunControlNow is important.
Well, as there are several gun shootings happening in the United States recently, such as Las Vegas, Texas, Orlando, Sandy Hooks, 