---
title: "Tweeter for Texas Shooting"
author: "Eunsik Na"
date: "November 15, 2017"
output: html_document
---

Words that address the shooting in Twitter

#prayfortexas
My heart is with the victims.
Heartbreaking
My thoughts and prayers are with texas. It is so heartbreaking, all these kind of tragedies are happening way too often.

Reasons why I think #prayfortexas is important.
There are several tweets dealing with consolation for shooting in texas occurred in November 5th, 2017. Of course if there is a tradegy such as shootings, people usually tweet on twiiter to comfort people who lost their friends or families in the event of shootings.


#GunControlNow
Here is a SINGLE reason why NOTHING is happening after these mass shootings. It's not the 2nd Amendment, It's Money & Greed.
When drunk driving became an issue, laws were written. Why is gun crime the ONLY thing govt. won't even talk about?! NRA = money.
Fact: Thoughts & prayers have never prevented a mass shooting. Laws have. 
Isn't is strange how mental illness doesn't massacre anyone in Canada, Australia, or the United Kingdom?

Reasons why I think #GunControlNow is important.
Well, as there are several gun shootings happening in the United States recently, such as Las Vegas, Texas, Orlando, Sandy Hooks, people start to arise their voice that there should be gun control immediately. Whenever there is a gun shooting, people just say "rest in peace. thoughts and prayer." However, that's it. No changes for laws related to guns. In other words, people do not care, especially for politicians. After 2~3 days have been passed, people forget those past events and guess what; those shooting events will occur again and another tradegies happen. So, this cycle is rolling and rolling which is very bad.

#NRAisATerroristOrganization
Terrorism in America: It’s not a brown people issue.
13k people killed by guns in USA in 2017 so far
308 Mass Shootings in USA in 2017 so far
People killed by Islamic Terror Attacks 6,713 WORLDWIDE yes Worldwide!
Strange how the rules change, based on the shooter. The hypocrisy is ridiculous. 

Reasons why I think #NRAisATerroristOrganization is important.
There are some tweets showing the datas. It demonstrates that people killed by American people in the United States is bigger than people killed by IS worldwide, not USA! This is very shocking fact. It means that there are more domestic acts of terror than international wise. Nevertheless, people in the U.S. do not really do anything if it's shooting. However, if it's terror like IS terror occurred in New York City on November 1st, 2017, then most politicans criticize and decide to make more strict for immigration.